# Generated by Django 5.1 on 2024-09-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FakeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=125)),
                ('company', models.CharField(max_length=225)),
                ('location', models.CharField(default=None, max_length=225)),
                ('salary', models.IntegerField(default=None)),
                ('emp_id', models.IntegerField(default=None)),
                ('address', models.CharField(max_length=225)),
            ],
        ),
    ]
